version: '3.9'

services:
  postgres:
    container_name: actionplanner-pg
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: moosess1234.
      POSTGRES_DB: actionplanner_db
      PGDATA: /data/postgresql
    ports:
      - "5433:5432"
    volumes:
      - ./data/pg:/data/postgresql
    restart: unless-stopped
