name: Add Issue to GitHub Projects v2

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to GitHub Projects (v2)
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueId = context.payload.issue.node_id;

            const projectId = "PVT_kwDODVyqM84A_bme";
            const statusFieldId = "PVTSSF_lADODVyqM84A_bmezgyiXug";
            const backlogOptionId = "f75ad846";

            const { data: addItem } = await github.graphql(`
              mutation($projectId:ID!, $contentId:ID!) {
                addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                  item {
                    id
                  }
                }
              }
            `, {
              projectId,
              contentId: issueId,
            });

            const itemId = addItem.addProjectV2ItemById.item.id;

            await github.graphql(`
              mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
                updateProjectV2ItemFieldValue(input: {
                  projectId: $projectId,
                  itemId: $itemId,
                  fieldId: $fieldId,
                  value: {
                    singleSelectOptionId: $optionId
                  }
                }) {
                  projectV2Item {
                    id
                  }
                }
              }
            `, {
              projectId,
              itemId,
              fieldId: statusFieldId,
              optionId: backlogOptionId,
            });
