name: Auto Assign Issue Creator

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest

    steps:
      - name: Assign issue creator
        uses: kentaro-m/auto-assign-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          assignees: |
            ${{ github.actor }}